import db from "../db.js";
import { emitMetric } from "../src/utils/metrics.js";
import { computeNext } from "../src/utils/schedule.js";
async function run() {
  try {
    // For each enabled rule, ensure next schedule exists up to 2 future occurrences
    const [rules] = await db
      .promise()
      .query("SELECT * FROM maintenance_rules WHERE enabled = 1");
    for (const rule of rules) {
      // Skip rules that use a sliding anchor — those should generate their
      // next schedule relative to the performed date (on completion), not
      // be pre-generated by the scheduler to avoid conflicting dates.
      if (
        rule.anchor_type &&
        String(rule.anchor_type).toLowerCase() === "sliding"
      ) {
        console.log(
          `Skipping sliding-anchor rule ${rule.id} (asset ${rule.asset_id})`
        );
        continue;
      }
      // Find last generated due_date for this rule
      const [lastRows] = await db
        .promise()
        .query(
          "SELECT due_date FROM maintenance_schedules WHERE rule_id = ? ORDER BY due_date DESC LIMIT 1",
          [rule.id]
        );
      let seedDate = rule.start_date;
      if (lastRows && lastRows.length > 0) seedDate = lastRows[0].due_date;

      // generate next occurrence (single upcoming schedule)
      for (let i = 0; i < 1; i++) {
        const next = computeNext(
          seedDate,
          rule.interval_value,
          rule.interval_unit
        );
        if (!next) break;
        // check existing schedule for same asset & due_date
        const [existing] = await db
          .promise()
          .query(
            "SELECT id, rule_id FROM maintenance_schedules WHERE asset_id = ? AND due_date = ? LIMIT 1",
            [rule.asset_id, next]
          );
        if (existing && existing.length > 0) {
          const ex = existing[0];
          if (ex.rule_id !== rule.id) {
            // compare priority
            const [pr] = await db
              .promise()
              .query("SELECT priority FROM maintenance_rules WHERE id = ?", [
                rule.id,
              ]);
            const [prEx] = await db
              .promise()
              .query("SELECT priority FROM maintenance_rules WHERE id = ?", [
                ex.rule_id,
              ]);
            const p = pr && pr.length > 0 ? pr[0].priority : 0;
            const pex = prEx && prEx.length > 0 ? prEx[0].priority : 0;
            if (p > pex) {
              // replace existing schedule's rule_id with higher priority rule
              await db
                .promise()
                .execute(
                  "UPDATE maintenance_schedules SET rule_id = ?, meta = ? WHERE id = ?",
                  [
                    rule.id,
                    JSON.stringify({
                      replaced_rule: ex.rule_id,
                      generated_from_rule: rule.id,
                    }),
                    ex.id,
                  ]
                );
            }
          }
        } else {
          // insert if none exists
          await db
            .promise()
            .execute(
              "INSERT IGNORE INTO maintenance_schedules (rule_id, asset_id, due_date, meta) VALUES (?, ?, ?, ?)",
              [
                rule.id,
                rule.asset_id,
                next,
                JSON.stringify({ generated_from_rule: rule.id }),
              ]
            );
        }
        seedDate = next;
      }
    }
    console.log("Schedule generation completed.");
    emitMetric("generateSchedules.run", 1, {
      status: "success",
      rules: rules.length,
    });
    process.exit(0);
  } catch (err) {
    console.error("Error generating schedules:", err);
    emitMetric("generateSchedules.run", 0, {
      status: "failure",
      error: String(err),
    });
    process.exit(1);
  }
}

// computeNext is provided by src/utils/schedule.js

run();
